config/routes.rb
Rails.application.routes.draw do

  resources :cates

  #get 'password_resets/new'
resources :password_resets

 
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users, except: [:index]
  get 'home/index'
  root 'home#index'

  resources :products
  #root 'products#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


get 'cates/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cate.rb
class Cate < ApplicationRecord
	has_many :product , dependent: :destroy

	validates :productname, presence: true, length: { minimum:2 ,maximum: 20 }
    #validates_format_of :productname, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
     validates :productname, :format => { with: /\A\w+\z/, :message => 'No Special characters, only letters and numbers' }
end

app/controllers/cates_controller.rb
class CatesController < ApplicationController
  before_action :set_cate, only: [:show, :edit, :update, :destroy]
  before_action :check

  def check
    if current_user.present?
      # redirect_to laptops_path
    else 
      redirect_to root_url
  end
end
  # GET /cates
  # GET /cates.json
  def index
    cates = Cate.select('productname')
    products = Product.select('name')

    @cc = cates.length
    @pc = products.length

    @cates = Cate.all
  end

  # GET /cates/1
  # GET /cates/1.json
  def show
    #binding.pry
    @cate = Cate.find_by(id: params[:id]).product.all
  end

  # GET /cates/new
  def new
    @cate = Cate.new
  end

  # GET /cates/1/edit
  def edit
  end

  # POST /cates
  # POST /cates.json
  def create
    @cate = Cate.new(cate_params)

    respond_to do |format|
      if @cate.save
        format.html { redirect_to @cate, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @cate }
      else
        format.html { render :new }
        format.json { render json: @cate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cates/1
  # PATCH/PUT /cates/1.json
  def update
    respond_to do |format|
      if @cate.update(cate_params)
        format.html { redirect_to @cate, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @cate }
      else
        format.html { render :edit }
        format.json { render json: @cate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cates/1
  # DELETE /cates/1.json
  def destroy
    #binding.pry
    @cate.destroy
    #redirect_to 'cate_path'
    render 'new'
    # respond_to do |format|
    #   format.html { redirect_to cates_url, notice: 'Cate was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cate
      @cate = Cate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cate_params
      params.require(:cate).permit(:productname)
    end
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/views/cates/_form.html.erb
<%= form_with(model: cate, local: true) do |form| %>
  <% if cate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cate.errors.count, "error") %> prohibited this cate from being saved:</h2>

      <ul>
      <% cate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>


<table>
  
  <tr>
    <td><%= form.label :category_name %></td>
     <td> <%= form.text_field :productname %></td>
   </tr>

  <tr>
    <td> <%= form.submit %></td>
  </tr>
  

</table>
    

 
<% end %>

app/views/cates/edit.html.erb
<h1>Editing Cate</h1>

<%= render 'form', cate: @cate %>

<%= link_to 'Show', @cate %> |
<%= link_to 'Back', cates_path %>

app/views/cates/index.html.erb
 Total number of Category  <%= @cc %> ,
 Total number of Product  <%= @pc %>
<hr>
<h3>Category</h3>

<p class="navbar-text float-right">
<%= link_to 'New Category', new_cate_path %> | <%= link_to 'New Product', new_product_path %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>Category</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cates.each do |cate| %>
      <tr>
        <td><%= cate.productname %></td>
        <td><%= link_to 'Show', cate_path(cate.id) %></td>
        <td><%= link_to 'Edit', edit_cate_path(cate.id) %></td>
        <td><%= link_to 'Destroy', cate_path(cate.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cates/new.html.erb
<h3>New Categories</h3>

<%= render 'form', cate: @cate %>

<%= link_to 'Back', cates_path %>

app/views/cates/show.html.erb
<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Date</th>
      <th>Edit</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    

     <% @cate.each do |cat| %>
    
           <tr>
        <td><%= cat.name %></td>
        <td><%= cat.description %></td>
               <td><%= image_tag cat.image_url, width: '20%' if cat.image.present? %></td>

        <td><%= cat.dat %></td>
        <td><%= link_to 'View', product_path(cat.id) %></td>
        <td><%= link_to 'Update', edit_product_path(cat.id) %></td>
        <td><%= link_to 'Delete', cat, method: :delete, data: {confirm: 'Are you sure?'} %></td> 

        
       </tr>
      <%end%>
    
  </tbody>
</table>

<br>




<%= link_to 'Add Product', new_product_path %> |

<%= link_to 'Edit', edit_cate_path(@cate) %> |
<%= link_to 'Back', cates_path %>