config/routes.rb
Rails.application.routes.draw do

  resources :cates

  #get 'password_resets/new'
resources :password_resets

 
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users, except: [:index]
  get 'home/index'
  root 'home#index'

  resources :products
  #root 'products#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


get 'cates/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :cate

  
  validates :name, presence: true, length: { maximum: 20 }, :format => { :with => /\A\w+\z/ }
  validates :description, presence: true, length: { maximum: 100 , minimum:10}
  validates :dat, presence: true
  validates_format_of :image,presence: true, :with => %r{\.(png|jpg|jpeg)}i, :message => "only .jpg .jpej ang .png"




end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  

  before_action :check

  def check
    if current_user.present?
      # redirect_to laptops_path
    else 
      redirect_to root_url
  end
end

  def index
    @products = Product.all
  end

  def show

  end
  
  def new
    @product = Product.new

  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
#   def create
#     #binding.pry
#    cate = Cate.find_by(productname: params["product"]["category"])
#     #binding.pry
#    a = params["product"]["category"]
#    pc = Cate.select('productname')
   
#    for i in 0...pc.length do
#     if a == pc[i]['productname']
#       @product = cate.product.new(product_params)

#       respond_to do |format|
#       if @product.save
#         format.html { redirect_to @product, notice: 'Product was successfully created.' }
#         format.json { render :show, status: :created, location: @product }
#        # else
#        #   format.html { render :new }
#        #   format.json { render json: @product.errors, status: :unprocessable_entity ,notice: 'Select Valid Category'}
#         end
#       end
#          break
#      end

     

#  end
# end
   #@product = cate.product.new(product_params)

    #@cate = Cate.new(params[:cate])
    #@cate.product.create(params[:product])
    
def create
  
  @product = Cate.find_by(id: params['categories']).product.new(product_params)
   
   respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
       else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity ,notice: 'Select Valid Category'}
        end
      end

end

    
  

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :description, :dat)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
     <tr>

       <td> <%= form.label :category %> </td>
       <td><%= select_tag "categories", options_from_collection_for_select(Cate.all, "id", "productname") %>
       </td>



  <tr>
     <td><%= form.label :name %></td>
     <td><%= form.text_field :name %></td>
  </tr>

  <tr>
    <td><%= form.label :image %></td>
    <td><%= form.file_field :image %></td>
  </tr>

   <tr>
    <td><%= form.label :description %></td>
    <td><%= form.text_field :description %></td>
  </tr>

<tr>
  <td> <%= form.label :dat %></td>
  <td><%= form.date_field :dat %></td>
</tr>

<tr>
  <td>  <%= form.submit %></td>
</tr>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3>Products</h3>
<p class="navbar-text float-right">
<%= link_to 'New Product', new_product_path %> | <%= link_to 'New Category', new_cate_path %> <br>
</p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Date</th>
      <th>Edit</th>
      <th>Show</th>
      <th>Delete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    

     <% @products.each do |product| %>
    
           <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
               <td><%= image_tag product.image_url, width: '20%' if product.image.present? %></td>

        <td><%= product.dat %></td>
        <td><%= link_to 'View', product %></td>
        <td><%= link_to 'Update', edit_product_path(product) %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
      <%end%>
    
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Image:</strong>
 <%= image_tag(@product.image_url, width: 300) if @product.image.present? %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Dat:</strong>
  <%= @product.dat %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>